package enum

var CODE = struct {
	SUCCESS string

	CUSTOMER_ERROR   string
	VALIDATION_ERROR string
	MISSING_TOKEN string
	INVALID_TOKEN string

	SYSTEM_ERROR string

	THIRD_PARTY_ERROR string
}{
	SUCCESS: "00000",

	CUSTOMER_ERROR:   "C0000",
	VALIDATION_ERROR: "C0001",
	MISSING_TOKEN: "C0002",
	INVALID_TOKEN: "C0003",

	SYSTEM_ERROR: "S0000",

	THIRD_PARTY_ERROR: "T0000",
}
