package enum

type SUCCESS struct{}

type CUSTOMER_ERROR struct{}
type VALIDATION_ERROR struct{}
type MISSING_TOKEN struct{}
type INVALID_TOKEN struct{}

type SYSTEM_ERROR struct{}
type GRPC_ERROR struct{}
type UNKNOWN_TRIGGER_MODE struct{}
type SERVICE_UNAVAILABLE struct{}
type EVENT_FALLBACKED struct{}
type EVENT_FAILED struct{}

type THIRD_PARTY_ERROR struct{}

const (
	CODE_SUCCESS Code = "00000"
	MSG_SUCCESS  Msg  = "Success"

	CODE_CUSTOMER_ERROR   Code = "C0000"
	MSG_CUSTOMER_ERROR    Msg  = "Customer Error"
	CODE_VALIDATION_ERROR Code = "C0001"
	MSG_VALIDATION_ERROR  Msg  = "Validation Error"
	CODE_MISSING_TOKEN    Code = "C0002"
	MSG_MISSING_TOKEN     Msg  = "Missing Token"
	CODE_INVALID_TOKEN    Code = "C0003"
	MSG_INVALID_TOKEN     Msg  = "Invalid Token"

	CODE_SYSTEM_ERROR         Code = "S0000"
	MSG_SYSTEM_ERROR          Msg  = "System Error"
	CODE_GRPC_ERROR           Code = "S0001"
	MSG_GRPC_ERROR            Msg  = "GRPC Error"
	CODE_UNKNOWN_TRIGGER_MODE Code = "S0002"
	MSG_UNKNOWN_TRIGGER_MODE  Msg  = "Unknown Trigger Mode"
	CODE_SERVICE_UNAVAILABLE  Code = "S0003"
	MSG_SERVICE_UNAVAILABLE   Msg  = "Service Unavailable"
	CODE_EVENT_FALLBACKED     Code = "S0004"
	MSG_EVENT_FALLBACKED      Msg  = "Event Fallbacked"
	CODE_EVENT_FAILED         Code = "S0005"
	MSG_EVENT_FAILED          Msg  = "Event Failed"

	CODE_THIRD_PARTY_ERROR Code = "T0000"
	MSG_THIRD_PARTY_ERROR  Msg  = "Third Party Error"
)

var STATUS_MAP StatusMap = StatusMap{
	SUCCESS{}: NewStatus(CODE_SUCCESS, MSG_SUCCESS),

	CUSTOMER_ERROR{}:   NewStatus(CODE_CUSTOMER_ERROR, MSG_CUSTOMER_ERROR),
	VALIDATION_ERROR{}: NewStatus(CODE_VALIDATION_ERROR, MSG_VALIDATION_ERROR),
	MISSING_TOKEN{}:    NewStatus(CODE_MISSING_TOKEN, MSG_MISSING_TOKEN),
	INVALID_TOKEN{}:    NewStatus(CODE_INVALID_TOKEN, MSG_INVALID_TOKEN),

	SYSTEM_ERROR{}:         NewStatus(CODE_SYSTEM_ERROR, MSG_SYSTEM_ERROR),
	GRPC_ERROR{}:           NewStatus(CODE_GRPC_ERROR, MSG_GRPC_ERROR),
	UNKNOWN_TRIGGER_MODE{}: NewStatus(CODE_UNKNOWN_TRIGGER_MODE, MSG_UNKNOWN_TRIGGER_MODE),
	SERVICE_UNAVAILABLE{}:  NewStatus(CODE_SERVICE_UNAVAILABLE, MSG_SERVICE_UNAVAILABLE),
	EVENT_FALLBACKED{}:     NewStatus(CODE_EVENT_FALLBACKED, MSG_EVENT_FALLBACKED),
	EVENT_FAILED{}:         NewStatus(CODE_EVENT_FAILED, MSG_EVENT_FAILED),

	THIRD_PARTY_ERROR{}: NewStatus(CODE_THIRD_PARTY_ERROR, MSG_THIRD_PARTY_ERROR),
}
