/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
	"time"
)

// checks if the CredentialListResponseCredentialsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialListResponseCredentialsInner{}

// CredentialListResponseCredentialsInner struct for CredentialListResponseCredentialsInner
type CredentialListResponseCredentialsInner struct {
	CredentialId *int64 `json:"credential_id,omitempty"`
	Type *string `json:"type,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewCredentialListResponseCredentialsInner instantiates a new CredentialListResponseCredentialsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialListResponseCredentialsInner() *CredentialListResponseCredentialsInner {
	this := CredentialListResponseCredentialsInner{}
	return &this
}

// NewCredentialListResponseCredentialsInnerWithDefaults instantiates a new CredentialListResponseCredentialsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialListResponseCredentialsInnerWithDefaults() *CredentialListResponseCredentialsInner {
	this := CredentialListResponseCredentialsInner{}
	return &this
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetCredentialId() int64 {
	if o == nil || IsNil(o.CredentialId) {
		var ret int64
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetCredentialIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given int64 and assigns it to the CredentialId field.
func (o *CredentialListResponseCredentialsInner) SetCredentialId(v int64) {
	o.CredentialId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CredentialListResponseCredentialsInner) SetType(v string) {
	o.Type = &v
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier) {
		var ret string
		return ret
	}
	return *o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.Identifier) {
		return nil, false
	}
	return o.Identifier, true
}

// HasIdentifier returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasIdentifier() bool {
	if o != nil && !IsNil(o.Identifier) {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given string and assigns it to the Identifier field.
func (o *CredentialListResponseCredentialsInner) SetIdentifier(v string) {
	o.Identifier = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *CredentialListResponseCredentialsInner) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *CredentialListResponseCredentialsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CredentialListResponseCredentialsInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponseCredentialsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CredentialListResponseCredentialsInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *CredentialListResponseCredentialsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o CredentialListResponseCredentialsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialListResponseCredentialsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Identifier) {
		toSerialize["identifier"] = o.Identifier
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableCredentialListResponseCredentialsInner struct {
	value *CredentialListResponseCredentialsInner
	isSet bool
}

func (v NullableCredentialListResponseCredentialsInner) Get() *CredentialListResponseCredentialsInner {
	return v.value
}

func (v *NullableCredentialListResponseCredentialsInner) Set(val *CredentialListResponseCredentialsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialListResponseCredentialsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialListResponseCredentialsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialListResponseCredentialsInner(val *CredentialListResponseCredentialsInner) *NullableCredentialListResponseCredentialsInner {
	return &NullableCredentialListResponseCredentialsInner{value: val, isSet: true}
}

func (v NullableCredentialListResponseCredentialsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialListResponseCredentialsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


