/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CredentialAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialAddRequest{}

// CredentialAddRequest struct for CredentialAddRequest
type CredentialAddRequest struct {
	Type string `json:"type"`
	Identifier string `json:"identifier"`
	Secret string `json:"secret"`
}

type _CredentialAddRequest CredentialAddRequest

// NewCredentialAddRequest instantiates a new CredentialAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialAddRequest(type_ string, identifier string, secret string) *CredentialAddRequest {
	this := CredentialAddRequest{}
	this.Type = type_
	this.Identifier = identifier
	this.Secret = secret
	return &this
}

// NewCredentialAddRequestWithDefaults instantiates a new CredentialAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialAddRequestWithDefaults() *CredentialAddRequest {
	this := CredentialAddRequest{}
	return &this
}

// GetType returns the Type field value
func (o *CredentialAddRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CredentialAddRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CredentialAddRequest) SetType(v string) {
	o.Type = v
}

// GetIdentifier returns the Identifier field value
func (o *CredentialAddRequest) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *CredentialAddRequest) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *CredentialAddRequest) SetIdentifier(v string) {
	o.Identifier = v
}

// GetSecret returns the Secret field value
func (o *CredentialAddRequest) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *CredentialAddRequest) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *CredentialAddRequest) SetSecret(v string) {
	o.Secret = v
}

func (o CredentialAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["identifier"] = o.Identifier
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *CredentialAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"identifier",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialAddRequest := _CredentialAddRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialAddRequest)

	if err != nil {
		return err
	}

	*o = CredentialAddRequest(varCredentialAddRequest)

	return err
}

type NullableCredentialAddRequest struct {
	value *CredentialAddRequest
	isSet bool
}

func (v NullableCredentialAddRequest) Get() *CredentialAddRequest {
	return v.value
}

func (v *NullableCredentialAddRequest) Set(val *CredentialAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialAddRequest(val *CredentialAddRequest) *NullableCredentialAddRequest {
	return &NullableCredentialAddRequest{value: val, isSet: true}
}

func (v NullableCredentialAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


