/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the CredentialListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialListResponse{}

// CredentialListResponse struct for CredentialListResponse
type CredentialListResponse struct {
	Credentials []CredentialListResponseCredentialsInner `json:"credentials,omitempty"`
}

// NewCredentialListResponse instantiates a new CredentialListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialListResponse() *CredentialListResponse {
	this := CredentialListResponse{}
	return &this
}

// NewCredentialListResponseWithDefaults instantiates a new CredentialListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialListResponseWithDefaults() *CredentialListResponse {
	this := CredentialListResponse{}
	return &this
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *CredentialListResponse) GetCredentials() []CredentialListResponseCredentialsInner {
	if o == nil || IsNil(o.Credentials) {
		var ret []CredentialListResponseCredentialsInner
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialListResponse) GetCredentialsOk() ([]CredentialListResponseCredentialsInner, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *CredentialListResponse) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given []CredentialListResponseCredentialsInner and assigns it to the Credentials field.
func (o *CredentialListResponse) SetCredentials(v []CredentialListResponseCredentialsInner) {
	o.Credentials = v
}

func (o CredentialListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}
	return toSerialize, nil
}

type NullableCredentialListResponse struct {
	value *CredentialListResponse
	isSet bool
}

func (v NullableCredentialListResponse) Get() *CredentialListResponse {
	return v.value
}

func (v *NullableCredentialListResponse) Set(val *CredentialListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialListResponse(val *CredentialListResponse) *NullableCredentialListResponse {
	return &NullableCredentialListResponse{value: val, isSet: true}
}

func (v NullableCredentialListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


