/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the CredentialAddResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialAddResponse{}

// CredentialAddResponse struct for CredentialAddResponse
type CredentialAddResponse struct {
	CredentialId *int64 `json:"credential_id,omitempty"`
}

// NewCredentialAddResponse instantiates a new CredentialAddResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialAddResponse() *CredentialAddResponse {
	this := CredentialAddResponse{}
	return &this
}

// NewCredentialAddResponseWithDefaults instantiates a new CredentialAddResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialAddResponseWithDefaults() *CredentialAddResponse {
	this := CredentialAddResponse{}
	return &this
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *CredentialAddResponse) GetCredentialId() int64 {
	if o == nil || IsNil(o.CredentialId) {
		var ret int64
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialAddResponse) GetCredentialIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *CredentialAddResponse) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given int64 and assigns it to the CredentialId field.
func (o *CredentialAddResponse) SetCredentialId(v int64) {
	o.CredentialId = &v
}

func (o CredentialAddResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialAddResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	return toSerialize, nil
}

type NullableCredentialAddResponse struct {
	value *CredentialAddResponse
	isSet bool
}

func (v NullableCredentialAddResponse) Get() *CredentialAddResponse {
	return v.value
}

func (v *NullableCredentialAddResponse) Set(val *CredentialAddResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialAddResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialAddResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialAddResponse(val *CredentialAddResponse) *NullableCredentialAddResponse {
	return &NullableCredentialAddResponse{value: val, isSet: true}
}

func (v NullableCredentialAddResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialAddResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


