/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the PermissionListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionListResponse{}

// PermissionListResponse struct for PermissionListResponse
type PermissionListResponse struct {
	Permissions []PermissionListResponsePermissionsInner `json:"permissions,omitempty"`
}

// NewPermissionListResponse instantiates a new PermissionListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionListResponse() *PermissionListResponse {
	this := PermissionListResponse{}
	return &this
}

// NewPermissionListResponseWithDefaults instantiates a new PermissionListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionListResponseWithDefaults() *PermissionListResponse {
	this := PermissionListResponse{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *PermissionListResponse) GetPermissions() []PermissionListResponsePermissionsInner {
	if o == nil || IsNil(o.Permissions) {
		var ret []PermissionListResponsePermissionsInner
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionListResponse) GetPermissionsOk() ([]PermissionListResponsePermissionsInner, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *PermissionListResponse) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []PermissionListResponsePermissionsInner and assigns it to the Permissions field.
func (o *PermissionListResponse) SetPermissions(v []PermissionListResponsePermissionsInner) {
	o.Permissions = v
}

func (o PermissionListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	return toSerialize, nil
}

type NullablePermissionListResponse struct {
	value *PermissionListResponse
	isSet bool
}

func (v NullablePermissionListResponse) Get() *PermissionListResponse {
	return v.value
}

func (v *NullablePermissionListResponse) Set(val *PermissionListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionListResponse(val *PermissionListResponse) *NullablePermissionListResponse {
	return &NullablePermissionListResponse{value: val, isSet: true}
}

func (v NullablePermissionListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


