/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the UserUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserUpdateResponse{}

// UserUpdateResponse struct for UserUpdateResponse
type UserUpdateResponse struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewUserUpdateResponse instantiates a new UserUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserUpdateResponse() *UserUpdateResponse {
	this := UserUpdateResponse{}
	return &this
}

// NewUserUpdateResponseWithDefaults instantiates a new UserUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserUpdateResponseWithDefaults() *UserUpdateResponse {
	this := UserUpdateResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UserUpdateResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUpdateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UserUpdateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UserUpdateResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UserUpdateResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserUpdateResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UserUpdateResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UserUpdateResponse) SetMessage(v string) {
	o.Message = &v
}

func (o UserUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableUserUpdateResponse struct {
	value *UserUpdateResponse
	isSet bool
}

func (v NullableUserUpdateResponse) Get() *UserUpdateResponse {
	return v.value
}

func (v *NullableUserUpdateResponse) Set(val *UserUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserUpdateResponse(val *UserUpdateResponse) *NullableUserUpdateResponse {
	return &NullableUserUpdateResponse{value: val, isSet: true}
}

func (v NullableUserUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


