/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
)

// checks if the UserCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreateResponse{}

// UserCreateResponse struct for UserCreateResponse
type UserCreateResponse struct {
	UserId *int64 `json:"user_id,omitempty"`
}

// NewUserCreateResponse instantiates a new UserCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateResponse() *UserCreateResponse {
	this := UserCreateResponse{}
	return &this
}

// NewUserCreateResponseWithDefaults instantiates a new UserCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateResponseWithDefaults() *UserCreateResponse {
	this := UserCreateResponse{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserCreateResponse) GetUserId() int64 {
	if o == nil || IsNil(o.UserId) {
		var ret int64
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateResponse) GetUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserCreateResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int64 and assigns it to the UserId field.
func (o *UserCreateResponse) SetUserId(v int64) {
	o.UserId = &v
}

func (o UserCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	return toSerialize, nil
}

type NullableUserCreateResponse struct {
	value *UserCreateResponse
	isSet bool
}

func (v NullableUserCreateResponse) Get() *UserCreateResponse {
	return v.value
}

func (v *NullableUserCreateResponse) Set(val *UserCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateResponse(val *UserCreateResponse) *NullableUserCreateResponse {
	return &NullableUserCreateResponse{value: val, isSet: true}
}

func (v NullableUserCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


