/*
User Management BFF API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package model

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserLoginRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserLoginRequest{}

// UserLoginRequest struct for UserLoginRequest
type UserLoginRequest struct {
	Username string `json:"username"`
	Email string `json:"email"`
	HashedPwd string `json:"hashed_pwd"`
}

type _UserLoginRequest UserLoginRequest

// NewUserLoginRequest instantiates a new UserLoginRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserLoginRequest(username string, email string, hashedPwd string) *UserLoginRequest {
	this := UserLoginRequest{}
	this.Username = username
	this.Email = email
	this.HashedPwd = hashedPwd
	return &this
}

// NewUserLoginRequestWithDefaults instantiates a new UserLoginRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserLoginRequestWithDefaults() *UserLoginRequest {
	this := UserLoginRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *UserLoginRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UserLoginRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UserLoginRequest) SetUsername(v string) {
	o.Username = v
}

// GetEmail returns the Email field value
func (o *UserLoginRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserLoginRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserLoginRequest) SetEmail(v string) {
	o.Email = v
}

// GetHashedPwd returns the HashedPwd field value
func (o *UserLoginRequest) GetHashedPwd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HashedPwd
}

// GetHashedPwdOk returns a tuple with the HashedPwd field value
// and a boolean to check if the value has been set.
func (o *UserLoginRequest) GetHashedPwdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HashedPwd, true
}

// SetHashedPwd sets field value
func (o *UserLoginRequest) SetHashedPwd(v string) {
	o.HashedPwd = v
}

func (o UserLoginRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserLoginRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["email"] = o.Email
	toSerialize["hashed_pwd"] = o.HashedPwd
	return toSerialize, nil
}

func (o *UserLoginRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"email",
		"hashed_pwd",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserLoginRequest := _UserLoginRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserLoginRequest)

	if err != nil {
		return err
	}

	*o = UserLoginRequest(varUserLoginRequest)

	return err
}

type NullableUserLoginRequest struct {
	value *UserLoginRequest
	isSet bool
}

func (v NullableUserLoginRequest) Get() *UserLoginRequest {
	return v.value
}

func (v *NullableUserLoginRequest) Set(val *UserLoginRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserLoginRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserLoginRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserLoginRequest(val *UserLoginRequest) *NullableUserLoginRequest {
	return &NullableUserLoginRequest{value: val, isSet: true}
}

func (v NullableUserLoginRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserLoginRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


