jwt:
  secret: prod
database:
  username: root
  password: 030212Lyx
  host: localhost
  port: 3306
  name: forum_shade
  uri: ${.username}:${.password}@(${.host}:${.port})/${.name}?charset=utf8mb4&parseTime=True&loc=Local
app:
  host: localhost
  port: 8080
  uri: ${.host}:${.port}